version: '3.9'
# PROJECT_NAME is stored in .env file
services:
  development:
    image: ${PROJECT_NAME:?err}:development
    container_name: ${PROJECT_NAME}-development
    build:
      target: development
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - src/main/resources/aws.secrets.properties
  test:
    image: ${PROJECT_NAME}:test
    container_name: ${PROJECT_NAME}-test
    build:
      target: test
    env_file:
      - src/main/resources/aws.secrets.properties
  verify:
    image: ${PROJECT_NAME}:verify
    container_name: ${PROJECT_NAME}-verify
    build:
      target: verify
    env_file:
      - src/main/resources/aws.secrets.properties
