version: '3.9'
services:
  development:
    container_name: development
    build:
        dockerfile: docker/Dockerfile
        target: development
    ports:
      - "8080:8080"
      - "5005:5005"
    env_file:
      - src/main/resources/aws.properties
  test:
    container_name: test
    build:
        dockerfile: docker/Dockerfile
        target: test
    env_file:
      - src/main/resources/aws.properties
  verify:
    container_name: verify
    build:
        dockerfile: docker/Dockerfile
        target: verify
    env_file:
      - src/main/resources/aws.properties
