version: '3.9'
services:
  development:
    container_name: development
    build:
        context: .
        dockerfile: docker/Dockerfile
        target: development
    ports:
      - "8080:8080"
    env_file:
      - src/main/resources/aws.properties
  test:
    container_name: test
    build:
        context: .
        dockerfile: docker/Dockerfile
        target: test
    env_file:
      - src/main/resources/aws.properties
