@startuml
'https://plantuml.com/class-diagram

legend top
    Project
        BI_JAVA_AWS
    Authors
        Yannick Baudraz
        Anthony Bouillant
endlegend

interface DataObject {
    + doesExist(objectPath : Path) : boolean
    + createObject(sourcePath : Path) : void
    + downloadObject(path : Path) : byte[]
    + publishObject(obj : object) : void
}

@enduml
