@startuml
'https://plantuml.com/class-diagram

legend top
    Project
        BI_JAVA_AWS
    Authors
        Yannick Baudraz
        Anthony Bouillant
endlegend

interface DataObject {
    + doesExist(obj : object) : boolean
    + createObject(obj : object) : void
    + downloadObject(path : string) : object
    + publishObject(obj : object) : void
}

@enduml
