name: Docker Image CI/CD

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create aws.properties file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './src/main/resources/aws.properties'
          property: |
            'aws.region'
            'aws.accessKeyId'
            'aws.secretAccessKey'
            'aws.bucketName'
          value: |
            '${{ secrets.AWS_REGION }}'
            '${{ secrets.AWS_ACCESSKEYID }}'
            '${{ secrets.AWS_SECRETACCESSKEY }}'
            '${{ secrets.AWS_BUCKETNAME }}'

      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Set environment variables
        run: | 
          echo "aws.region=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV \
          echo "aws.accessKeyId=${{ secrets.AWS_ACCESSKEYID }}" >> $GITHUB_ENV \
          echo "aws.secretAccessKey=${{ secrets.AWS_SECRETACCESSKEY }}" >> $GITHUB_ENV \
          echo "aws.AWS_BUCKETNAME=${{ secrets.AWS_BUCKETNAME }}" >> $GITHUB_ENV \

      - name: Run tests
        env:
          aws.accessKeyId: ${{ secrets.AWS_ACCESSKEYID }}
          aws.region: ${{ secrets.AWS_REGION }}
          aws.secretAccessKey: ${{ secrets.AWS_SECRETACCESSKEY }}
          aws.bucketName: ${{ secrets.AWS_BUCKETNAME }}
        run: mvn -B test --file pom.xml