name: Docker Image CI/CD

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml
      PROPERTY_FILE: src/main/resources/aws.properties

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Set environment variables
        run: |
          echo "aws.region=${{ secrets.AWS_REGION }}" >> $PROPERTY_FILE \
          echo "aws.accessKeyId=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $PROPERTY_FILE \
          echo "aws.secretAccessKey=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $PROPERTY_FILE \
          echo "aws.AWS_BUCKETNAME=${{ secrets.AWS_BUCKET_NAME }}" >> $PROPERTY_FILE \

      - name: Build and test
        run: mvn clean test