name: Docker Image CI/CD

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml
      aws.region: ${{ secrets.AWS_REGION }}
      aws.access_key_id: ${{ secrets.AWS_ACCESSKEYID }}
      aws.secret_access_key: ${{ secrets.AWS_SECRETACCESSKEY }}
      aws.bucketName: ${{ secrets.AWS_BUCKETNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose run test