name: Docker Image CI/CD

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create aws.properties file from secrets
        run: |
          echo "aws.region="${{ secrets.AWS_REGION }} >> ./src/main/resources/aws.properties
          echo "aws.secretAccessKey="${{ secrets.AWS_ACCESSKEYID }} >> ./src/main/resources/aws.properties
          echo "aws.accessKeyId="${{ secrets.AWS_SECRETACCESSKEY }} >> ./src/main/resources/aws.properties
          echo "aws.bucketName="${{ secrets.AWS_BUCKETNAME }} >> ./src/main/resources/aws.properties

      - name: cat aws.properties
        run: cat ./src/main/resources/aws.properties

      - name: echo secrets
        run: echo ${{ secrets.AWS_REGION }}

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose run test