name: Docker Image CI/CD

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: ./docker-compose.yml

    steps:
      - name: Write value to Properties-file
        uses: christian-draeger/write-properties@1.1.0
        with:
          path: './src/main/resources/aws.properties'
          property: |
            'aws.region'
            'aws.accessKeyId'
            'aws.secretAccessKey'
            'aws.bucketName'
          value: |
            '${{ secrets.AWS_REGION }}'
            '${{ secrets.AWS_ACCESSKEYID }}'
            '${{ secrets.AWS_SECRETACCESSKEY }}'
            '${{ secrets.AWS_BUCKETNAME }}'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose run test