name: Docker Image CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  test:
    name: Run test suite and verify code coverage
    runs-on: ubuntu-latest
    env:
      SECRET_FILE: src/main/resources/aws.secrets.properties
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --tag bi_aws_microservice --target verify

      - name: Run the integrations tests
        run: docker run --env-file ${{ env.PROPERTY_FILE }} bi_aws_microservice:latest
